services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - kuma:/app/data
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    restart: unless-stopped
    
volumes:
  kuma:
